#pragma once
#include "raylib.h"

namespace bubbleColors {
	//inline Color BACKGROUND = {30, 106, 71,255};
	inline Color BACKGROUND = WHITE;
	inline Color BUBBLE_EVEN = {215, 215, 215, 255};
	inline Color BUBBLE_UNEVEN = {194, 194, 194, 194};
	inline Color POSITIVE_EVEN = BUBBLE_EVEN;
	inline Color POSITIVE_UNEVEN = BUBBLE_UNEVEN;
	inline Color NEGATIVE_EVEN = BUBBLE_EVEN;
	inline Color NEGATIVE_UNEVEN = BUBBLE_UNEVEN;
	inline Color UNIT_TEXT_POSITIVE = BLACK;
	inline Color UNIT_TEXT_NEGATIVE = BLUE;
	inline Color VARIABLE_TEXT_POSITIVE = BLACK;
	inline Color VARIABLE_TEXT_NEGATIVE = BLUE;
	inline Color MULTIPLICATION_TEXT = ORANGE;
	inline Color MULTIPLICATION_EVEN = {190,234, 197,255};
	inline Color MULTIPLICATION_UNEVEN = {221, 249, 204, 255};
	inline Color POWER_TEXT = ORANGE;
	inline Color POWER_EVEN = MULTIPLICATION_EVEN;
	inline Color POWER_UNEVEN = MULTIPLICATION_UNEVEN;
	inline Color EQUALS_TEXT = BLACK;
	inline Color EQUALS_EVEN = BUBBLE_EVEN;
	inline Color EQUALS_UNEVEN = BUBBLE_UNEVEN;
	inline Color INEQUALS_TEXT = BLACK;
	inline Color INEQUALS_EVEN = BUBBLE_EVEN;
	inline Color INEQUALS_UNEVEN = BUBBLE_UNEVEN;
	inline Color SUMMATION_TEXT = ORANGE;
	inline Color SUMMATION_EVEN = MULTIPLICATION_EVEN;
	inline Color SUMMATION_UNEVEN = MULTIPLICATION_UNEVEN;
	inline Color FUNCTION_TEXT = ORANGE;
	inline Color FUNCTION_EVEN = MULTIPLICATION_EVEN;
	inline Color FUNCTION_UNEVEN = MULTIPLICATION_UNEVEN;
}